services:
  - type: web
    name: Notion Blog Publisher
    env: node
    plan: starter
    buildCommand: yarn install && yarn build    
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: NOTION_TOKEN
        value: secret_magyJ8fLT7ByvClJBJYqOzSEj7ZIPG9pnDmvz0arqeS
